### ISSUE TITLE
node-gyp rebuild failed

### ISSUE THREAD

**Issue by Jonybang** [galtproject/geesome-node#383]
error /home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.4 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/jonybang/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jonybang/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jonybang/.cache/node-gyp/12.18.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jonybang/.cache/node-gyp/12.18.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/jonybang/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jonybang/.cache/node-gyp/12.18.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:202,
                 from ../src/addon.cpp:4:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:18:51: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
      |                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
   22 | X(Boolean)
      | ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2664:59: note: declared here
 2664 |                 V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
      |                                                           ^~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:202,
                 from ../src/addon.cpp:4:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
      |                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
   40 | X(bool, Boolean)
      | ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2702:51: note: declared here
 2702 |                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
      |                                                   ^~~~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/addon.cpp:4:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
  103 |   return scope.Escape(v8::Function::New( isolate
      |                                          ^~~~~~~
      |                                          |
      |                                          v8::Isolate*
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:4276:22: note:   initializing argument 1 of ‘static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)’
 4276 |       Local<Context> context, FunctionCallback callback,
      |       ~~~~~~~~~~~~~~~^~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/addon.cpp:4:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                     ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:5531:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
 5531 |   static Local<Value> New(Isolate* isolate, Local<String> value);
      |                       ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:5531:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/addon.cpp:4:
../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                          ^
../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                            ^
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
 1034 |       v8::Local<v8::String> string = from->ToString();
      |                                                     ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2668:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2668 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2668:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2684:31: note: candidate: ‘v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const’
 2684 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2684:31: note:   candidate expects 1 argument, 0 provided
 2684 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
 1044 |         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
      |                                     ^~~~
      |                                     |
      |                                     char*
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2878:26: note:   initializing argument 1 of ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
 2878 |   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
      |                 ~~~~~~~~~^~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1818:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1818 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
      |                                                                ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3499:22: note: declared here
 3499 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1824:42: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1824 |     New(persistentHandle)->Set(key, value);
      |                                          ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3499:22: note: declared here
 3499 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1830:44: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1830 |     New(persistentHandle)->Set(index, value);
      |                                            ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3508:22: note: declared here
 3508 |                 bool Set(uint32_t index, Local<Value> value));
      |                      ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1836:61: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1836 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
      |                                                             ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3553:51: note: declared here
 3553 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
../../nan/nan.h:1842:55: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1842 |     return scope.Escape(New(persistentHandle)->Get(key));
      |                                                       ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3553:51: note: declared here
 3553 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../../nan/nan.h:1847:57: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1847 |     return scope.Escape(New(persistentHandle)->Get(index));
      |                                                         ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:3557:51: note: declared here
 3557 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
      |                                                   ^~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2167 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /usr/include/c++/9/cassert:44,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../src/addon.cpp:4:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
In file included from ../../nan/nan.h:2657,
                 from ../src/addon.cpp:4:
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:67:34: warning: ‘void v8::PersistentBase<T>::MarkIndependent() [with T = v8::Object]’ is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
   67 |     persistent().MarkIndependent();
      |                                  ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:570:22: note: declared here
  570 |       V8_INLINE void MarkIndependent());
      |                      ^~~~~~~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from /usr/include/c++/9/cassert:44,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../src/addon.cpp:4:
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  124 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:36:64: error: no matching function for call to ‘v8::Value::Int32Value()’
   36 |   hashlen = info[0]->IsUndefined() ? 512 : info[0]->Int32Value();
      |                                                                ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2709:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2709 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2709:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cpp:49:23: warning: ‘new’ of type ‘SHA3Hash’ with extended alignment 32 [-Waligned-new=]
   49 |    obj = new SHA3Hash();
      |                       ^
../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
../src/addon.cpp: In static member function ‘static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/addon.cpp:76:36: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   76 |   constructor.Reset(t->GetFunction());
      |                                    ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/addon.cpp:77:77: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   77 |   target->Set(Nan::New<String>("SHA3Hash").ToLocalChecked(), t->GetFunction());
      |                                                                             ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::Update(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:97:49: error: no matching function for call to ‘v8::Value::ToObject()’
   97 |    Local<Object> buffer_obj = info[0]->ToObject();
      |                                                 ^
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8-internal.h:14,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/jonybang/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/addon.cpp:1:
../src/addon.cpp: At global scope:
/home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:608:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  608 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/jonybang/.cache/node-gyp/12.18.4/include/node/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
  642 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cpp:164:1: note: in expansion of macro ‘NODE_MODULE’
  164 | NODE_MODULE(sha3, SHA3Hash::Init)
      | ^~~~~~~~~~~
make: *** [sha3.target.mk:115: Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jonybang/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-58-generic
gyp ERR! command "/home/jonybang/.nvm/versions/node/v12.18.4/bin/node" "/home/jonybang/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jonybang/workspace/geesome-node/frontend/node_modules/keccakjs/node_modules/sha3

**Comment by Jonybang** [comment]
Currently node-gyp not working correctly in 12 version of nodeJS, but we can use 10 version of nodeJS and will try get rid of node-gyp dependencies
